name: Check Formatting

on:
  push:

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Formatting Check
        uses: dprint/check@v2.2
